name: walletman
description: A personal finance management application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  fl_chart: ^0.6.0
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.5.0
  flutter_screenutil: ^0.6.1
  sqflite: ^1.1.7+3
  path_provider: ^1.4.5
  persian_datetime_picker: ^1.0.0
  charts_flutter: ^0.8.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/woman.png
    - assets/imgs/digipay.png
    - assets/imgs/Banks/ansar.png
    - assets/imgs/Banks/egtesad.png
    - assets/imgs/Banks/karafarin.png
    - assets/imgs/Banks/keshavarzi.png
    - assets/imgs/Banks/maskan.png
    - assets/imgs/Banks/mellat.png
    - assets/imgs/Banks/melli.png
    - assets/imgs/Banks/pars.png
    - assets/imgs/Banks/parsargard.png
    - assets/imgs/Banks/saderat.png
    - assets/imgs/Banks/saman.png
    - assets/imgs/Banks/sanat.png
    - assets/imgs/Banks/sarmayeh.png
    - assets/imgs/Banks/sepah.png
    - assets/imgs/Banks/sina.png
    - assets/imgs/Banks/tejarat.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/IRANSans.ttf
        - asset: assets/fonts/IRANSans_Black.ttf
        - asset: assets/fonts/IRANSans_Bold.ttf
        - asset: assets/fonts/IRANSans_Light.ttf
        - asset: assets/fonts/IRANSans_Medium.ttf
          style: italic
    - family: IranYekan
      fonts:
        - asset: assets/fonts/IRANYekanBold.ttf
        - asset: assets/fonts/IRANYekanRegular.ttf
          weight: 700
    - family: Gugi
      fonts:
        - asset: assets/fonts/Gugi-Regular.ttf
          weight: 700
    - family: Bkoodak
      fonts:
        - asset: assets/fonts/B_Koodak_Bold_0.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
